USER_ID = 'myuser'
# Your PAT (Personal Access Token) can be found in the portal under Authentification
PAT = '1234'
APP_ID = 'abcdef'
WORKFLOW_ID = 'Clarifai_WORKFLOW_ID'
WORKFLOW_ID_TEXT = 'Clarifai_WORKFLOW_ID'
WORKFLOW_ID_IMAGE = 'Clarifai_WORKFLOW_ID'
WORKFLOW_ID_STORY_GPT3 = 'Clarifai_WORKFLOW_ID'
